using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Sharpen.Analyzer.Analyzers.CSharp8;

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class EnableNullableContextAndDeclareIdentifierAsNullableAnalyzer : DiagnosticAnalyzer
{
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
        ImmutableArray.Create(Rules.Rules.EnableNullableContextAndDeclareIdentifierAsNullableRule);

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();

        context.RegisterSyntaxNodeAction(AnalyzeNode,
            SyntaxKind.SimpleAssignmentExpression,
            SyntaxKind.EqualsExpression,
            SyntaxKind.NotEqualsExpression,
            SyntaxKind.VariableDeclarator,
            SyntaxKind.ConditionalAccessExpression,
            SyntaxKind.CoalesceExpression,
            SyntaxKind.Parameter,
            SyntaxKind.PropertyDeclaration);
    }

    private static void AnalyzeNode(SyntaxNodeAnalysisContext context)
    {
        var symbol = GetNullableIdentifierSymbol(context);
        if (symbol is null || symbol.IsImplicitlyDeclared)
            return;

        // Legacy analyzer was project-wide and had a lot of infrastructure around it.
        // In this repository we keep the behavior minimal and conservative:
        // - only report when the identifier is declared in the same syntax tree
        // - skip generated code
        // - do not attempt to detect whether nullable context is already enabled
        var declaringSyntax = symbol.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax(context.CancellationToken);
        if (declaringSyntax is null)
            return;

        if (!ReferenceEquals(declaringSyntax.SyntaxTree, context.Node.SyntaxTree))
            return;

        if (context.Node.SyntaxTree.FilePath is { Length: > 0 } filePath)
        {
            if (Common.GeneratedCodeDetection.IsGeneratedFile(filePath) ||
                Common.SyntaxTreeExtensions.BeginsWithAutoGeneratedComment(context.Node.SyntaxTree))
            {
                return;
            }
        }

        if (!IdentifierIsAlreadyNullable(symbol))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                Rules.Rules.EnableNullableContextAndDeclareIdentifierAsNullableRule,
                declaringSyntax.GetLocation()));
        }
    }

    private static bool IdentifierIsAlreadyNullable(ISymbol symbol)
    {
        // Legacy implementation (VS2017) treated value types as already nullable (Nullable<T>).
        // We keep the same conservative behavior.
        return symbol switch
        {
            IFieldSymbol field => field.Type.IsValueType,
            IPropertySymbol property => property.Type.IsValueType,
            IParameterSymbol parameter => parameter.Type.IsValueType,
            ILocalSymbol local => local.Type.IsValueType,
            _ => true
        };
    }

    private static ISymbol? GetNullableIdentifierSymbol(SyntaxNodeAnalysisContext context)
    {
        var node = context.Node;
        var semanticModel = context.SemanticModel;

        switch (node)
        {
            case AssignmentExpressionSyntax assignment:
                return IsSurelyNullable(assignment.Right) && IsIdentifierOrPropertyAccess(assignment.Left)
                    ? semanticModel.GetSymbolInfo(assignment.Left, context.CancellationToken).Symbol
                    : null;

            case BinaryExpressionSyntax binaryExpression:
                switch (binaryExpression.Kind())
                {
                    case SyntaxKind.EqualsExpression:
                    case SyntaxKind.NotEqualsExpression:
                        if (IsSurelyNullable(binaryExpression.Right) && IsIdentifierOrPropertyAccess(binaryExpression.Left))
                            return semanticModel.GetSymbolInfo(binaryExpression.Left, context.CancellationToken).Symbol;
                        if (IsSurelyNullable(binaryExpression.Left) && IsIdentifierOrPropertyAccess(binaryExpression.Right))
                            return semanticModel.GetSymbolInfo(binaryExpression.Right, context.CancellationToken).Symbol;
                        return null;

                    case SyntaxKind.CoalesceExpression:
                        return IsIdentifierOrPropertyAccess(binaryExpression.Left)
                            ? semanticModel.GetSymbolInfo(binaryExpression.Left, context.CancellationToken).Symbol
                            : null;

                    default:
                        return null;
                }

            case VariableDeclaratorSyntax variableDeclarator:
                return IsSurelyNullable(variableDeclarator.Initializer?.Value) &&
                       variableDeclarator.Identifier.IsKind(SyntaxKind.IdentifierToken)
                    ? semanticModel.GetDeclaredSymbol(variableDeclarator, context.CancellationToken)
                    : null;

            case ConditionalAccessExpressionSyntax conditionalAccess:
                return IsIdentifierOrPropertyAccess(conditionalAccess.Expression)
                    ? semanticModel.GetSymbolInfo(conditionalAccess.Expression, context.CancellationToken).Symbol
                    : null;

            case ParameterSyntax parameter:
                return IsSurelyNullable(parameter.Default?.Value)
                    ? semanticModel.GetDeclaredSymbol(parameter, context.CancellationToken)
                    : null;

            case PropertyDeclarationSyntax propertyDeclaration:
                return IsSurelyNullable(propertyDeclaration.Initializer?.Value)
                    ? semanticModel.GetDeclaredSymbol(propertyDeclaration, context.CancellationToken)
                    : null;

            default:
                return null;
        }

        static bool IsSurelyNullable(SyntaxNode? potentiallyNullableNode)
        {
            return potentiallyNullableNode?.IsKind(SyntaxKind.NullLiteralExpression) == true ||
                   potentiallyNullableNode?.IsKind(SyntaxKind.DefaultLiteralExpression) == true ||
                   potentiallyNullableNode?.IsKind(SyntaxKind.DefaultExpression) == true ||
                   potentiallyNullableNode?.IsKind(SyntaxKind.AsExpression) == true;
        }

        static bool IsIdentifierOrPropertyAccess(SyntaxNode? syntaxNode)
        {
            return syntaxNode?.IsKind(SyntaxKind.IdentifierName) == true ||
                   syntaxNode?.IsKind(SyntaxKind.SimpleMemberAccessExpression) == true;
        }
    }
}
