using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Sharpen.Analyzer.Common;

namespace Sharpen.Analyzer.Analyzers.CSharp8;

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class EnableNullableContextAndDeclareIdentifierAsNullableAnalyzer : DiagnosticAnalyzer
{
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
        ImmutableArray.Create(Rules.GeneralRules.EnableNullableContextAndDeclareIdentifierAsNullableRule);

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();

        context.RegisterSyntaxNodeAction(AnalyzeNode,
            SyntaxKind.SimpleAssignmentExpression,
            SyntaxKind.EqualsExpression,
            SyntaxKind.NotEqualsExpression,
            SyntaxKind.VariableDeclarator,
            SyntaxKind.ConditionalAccessExpression,
            SyntaxKind.CoalesceExpression,
            SyntaxKind.Parameter,
            SyntaxKind.PropertyDeclaration);
    }

    private static void AnalyzeNode(SyntaxNodeAnalysisContext context)
    {
        var symbol = GetNullableIdentifierSymbol(context);
        if (symbol?.IsImplicitlyDeclared != false)
            return;

        // Legacy analyzer was project-wide and had a lot of infrastructure around it.
        // In this repository we keep the behavior minimal and conservative:
        // - only report when the identifier is declared in the same syntax tree
        // - skip generated code
        // - do not attempt to detect whether nullable context is already enabled
        var declaringSyntax = symbol.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax(context.CancellationToken);
        if (declaringSyntax is null)
            return;

        if (!ReferenceEquals(declaringSyntax.SyntaxTree, context.Node.SyntaxTree))
            return;

        if (context.Node.SyntaxTree.FilePath is { Length: > 0 } filePath)
        {
            if (GeneratedCodeDetection.IsGeneratedFile(filePath) ||
                context.Node.SyntaxTree.BeginsWithAutoGeneratedComment())
            {
                return;
            }
        }

        if (!IdentifierIsAlreadyNullable(symbol))
        {
            // Report on the triggering node location (assignment/initializer/etc.) to keep the diagnostic "local"
            // for the code-fix test harness. The code fix provider will resolve the symbol and update the
            // declaration type.
            context.ReportDiagnostic(Diagnostic.Create(
                Rules.GeneralRules.EnableNullableContextAndDeclareIdentifierAsNullableRule,
                context.Node.GetLocation()));
        }
    }

    private static bool IdentifierIsAlreadyNullable(ISymbol symbol)
    {
        // If the type is already annotated (string?), do not report.
        // If it's a value type, we also do not report (legacy behavior treated value types as already nullable).
        return symbol switch
        {
            IFieldSymbol field => field.Type.IsValueType || field.NullableAnnotation == NullableAnnotation.Annotated,
            IPropertySymbol property => property.Type.IsValueType ||
                                        property.NullableAnnotation == NullableAnnotation.Annotated,
            IParameterSymbol parameter => parameter.Type.IsValueType ||
                                          parameter.NullableAnnotation == NullableAnnotation.Annotated,
            ILocalSymbol local => local.Type.IsValueType || local.NullableAnnotation == NullableAnnotation.Annotated,
            _ => true
        };
    }

    private static ISymbol? GetNullableIdentifierSymbol(SyntaxNodeAnalysisContext context)
    {
        return context.Node switch
        {
            AssignmentExpressionSyntax assignment => GetNullableSymbolFromAssignment(context, assignment),
            BinaryExpressionSyntax binaryExpression => GetNullableSymbolFromBinaryExpression(context, binaryExpression),
            VariableDeclaratorSyntax variableDeclarator => GetNullableSymbolFromVariableDeclarator(context, variableDeclarator),
            ConditionalAccessExpressionSyntax conditionalAccess => GetNullableSymbolFromConditionalAccess(context, conditionalAccess),
            ParameterSyntax parameter => GetNullableSymbolFromParameter(context, parameter),
            PropertyDeclarationSyntax propertyDeclaration => GetNullableSymbolFromProperty(context, propertyDeclaration),
            _ => null
        };

        static bool IsSurelyNullable(SyntaxNode? potentiallyNullableNode)
        {
            return potentiallyNullableNode.IsKind(SyntaxKind.NullLiteralExpression) ||
                   potentiallyNullableNode.IsKind(SyntaxKind.DefaultLiteralExpression) ||
                   potentiallyNullableNode.IsKind(SyntaxKind.DefaultExpression) ||
                   potentiallyNullableNode.IsKind(SyntaxKind.AsExpression);
        }

        static bool IsIdentifierOrPropertyAccess(SyntaxNode? syntaxNode)
        {
            return syntaxNode.IsKind(SyntaxKind.IdentifierName) ||
                   syntaxNode.IsKind(SyntaxKind.SimpleMemberAccessExpression);
        }
    }

    private static ISymbol? GetNullableSymbolFromAssignment(
        SyntaxNodeAnalysisContext context,
        AssignmentExpressionSyntax assignment)
    {
        return IsSurelyNullable(assignment.Right) && IsIdentifierOrPropertyAccess(assignment.Left)
            ? context.SemanticModel.GetSymbolInfo(assignment.Left, context.CancellationToken).Symbol
            : null;
    }

    private static ISymbol? GetNullableSymbolFromBinaryExpression(
        SyntaxNodeAnalysisContext context,
        BinaryExpressionSyntax binaryExpression)
    {
        return binaryExpression.Kind() switch
        {
            SyntaxKind.EqualsExpression or SyntaxKind.NotEqualsExpression =>
                GetNullableSymbolFromEquality(context, binaryExpression),
            SyntaxKind.CoalesceExpression => IsIdentifierOrPropertyAccess(binaryExpression.Left)
                ? context.SemanticModel.GetSymbolInfo(binaryExpression.Left, context.CancellationToken).Symbol
                : null,
            _ => null
        };
    }

    private static ISymbol? GetNullableSymbolFromEquality(
        SyntaxNodeAnalysisContext context,
        BinaryExpressionSyntax binaryExpression)
    {
        if (IsSurelyNullable(binaryExpression.Right) && IsIdentifierOrPropertyAccess(binaryExpression.Left))
            return context.SemanticModel.GetSymbolInfo(binaryExpression.Left, context.CancellationToken).Symbol;

        return IsSurelyNullable(binaryExpression.Left) && IsIdentifierOrPropertyAccess(binaryExpression.Right)
            ? context.SemanticModel.GetSymbolInfo(binaryExpression.Right, context.CancellationToken).Symbol
            : null;
    }

    private static ISymbol? GetNullableSymbolFromVariableDeclarator(
        SyntaxNodeAnalysisContext context,
        VariableDeclaratorSyntax variableDeclarator)
    {
        return IsSurelyNullable(variableDeclarator.Initializer?.Value)
               && variableDeclarator.Identifier.IsKind(SyntaxKind.IdentifierToken)
            ? context.SemanticModel.GetDeclaredSymbol(variableDeclarator, context.CancellationToken)
            : null;
    }

    private static ISymbol? GetNullableSymbolFromConditionalAccess(
        SyntaxNodeAnalysisContext context,
        ConditionalAccessExpressionSyntax conditionalAccess)
    {
        return IsIdentifierOrPropertyAccess(conditionalAccess.Expression)
            ? context.SemanticModel.GetSymbolInfo(conditionalAccess.Expression, context.CancellationToken).Symbol
            : null;
    }

    private static ISymbol? GetNullableSymbolFromParameter(
        SyntaxNodeAnalysisContext context,
        ParameterSyntax parameter)
    {
        return IsSurelyNullable(parameter.Default?.Value)
            ? context.SemanticModel.GetDeclaredSymbol(parameter, context.CancellationToken)
            : null;
    }

    private static ISymbol? GetNullableSymbolFromProperty(
        SyntaxNodeAnalysisContext context,
        PropertyDeclarationSyntax propertyDeclaration)
    {
        return IsSurelyNullable(propertyDeclaration.Initializer?.Value)
            ? context.SemanticModel.GetDeclaredSymbol(propertyDeclaration, context.CancellationToken)
            : null;
    }

    private static bool IsSurelyNullable(SyntaxNode? potentiallyNullableNode)
    {
        return potentiallyNullableNode.IsKind(SyntaxKind.NullLiteralExpression) ||
               potentiallyNullableNode.IsKind(SyntaxKind.DefaultLiteralExpression) ||
               potentiallyNullableNode.IsKind(SyntaxKind.DefaultExpression) ||
               potentiallyNullableNode.IsKind(SyntaxKind.AsExpression);
    }

    private static bool IsIdentifierOrPropertyAccess(SyntaxNode? syntaxNode)
    {
        return syntaxNode.IsKind(SyntaxKind.IdentifierName) ||
               syntaxNode.IsKind(SyntaxKind.SimpleMemberAccessExpression);
    }
}
