# As the project Sample is exactly containing samples that triggers analysis and code fixes, it contains a lot of findings on purpose. We ignore it in SonarQube
sonar.exclusions=Sharpen.Analyzer/Sharpen.Analyzer/Sharpen.Analyzer.Sample/**
