using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Sharpen.Analyzer.Common;

public static class SyntaxTreeExtensions
{
    public static bool BeginsWithAutoGeneratedComment(this SyntaxTree syntaxTree)
    {
        var root = syntaxTree.GetRoot();
        var firstToken = root.GetFirstToken(true);

        var leadingTrivia = firstToken.LeadingTrivia;
        return (from trivia in leadingTrivia where trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) || trivia.IsKind(SyntaxKind.MultiLineCommentTrivia) select trivia.ToFullString()).Any(text => text.IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0);
    }
}