using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Sharpen.Analyzer.Common;

public static class SyntaxTreeExtensions
{
    public static bool BeginsWithAutoGeneratedComment(this SyntaxTree syntaxTree)
    {
        var root = syntaxTree.GetRoot();
        var firstToken = root.GetFirstToken(includeZeroWidth: true);

        var leadingTrivia = firstToken.LeadingTrivia;
        foreach (var trivia in leadingTrivia)
        {
            if (!trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) &&
                !trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
            {
                continue;
            }

            var text = trivia.ToFullString();
            if (text.IndexOf("<auto-generated", System.StringComparison.OrdinalIgnoreCase) >= 0)
                return true;
        }

        return false;
    }
}
